name: update-data
on:
  schedule: [{ cron: '*/5 * * * *' }]
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      INSPECTION_DATASET_URL: https://raw.githubusercontent.com/tottori-covid19/dataset/master/tottori/inspection.csv
      QUERENT_DATASET_URL: https://raw.githubusercontent.com/tottori-covid19/dataset/master/tottori/querent.csv
    steps:
      - uses: actions/checkout@v2
      - run: curl -sL -o tool/downloads/tottori/inspection.csv "${INSPECTION_DATASET_URL}"
      - run: curl -sL -o tool/downloads/tottori/querent.csv "${QUERENT_DATASET_URL}"
      - id: git_status
        run: echo "::set-output name=mod::$(git status --porcelain)"
      - if: steps.git_status.outputs.mod != ''
        uses: actions/cache@v1
        with:
          path: tool/node_modules
          key: yarn-${{ hashFiles('tool/yarn.lock') }}
          restore-keys: yarn-
      - if: steps.git_status.outputs.mod != ''
        run: |
          yarn --cwd tool \
          && yarn --cwd tool node main.js \
          && git add data/data.json \
          && git \
            -c "user.name=${GITHUB_ACTOR}" \
            -c "user.email=${GITHUB_ACTOR}@users.noreply.github.com" \
            commit -m "${{ github.workflow }}" \
          && git push origin HEAD
